### ISSUE TITLE
Stinger is in similar a way hooking method

### ISSUE THREAD

**Issue by Assuner-Lee** [yulingtianxia/BlockHook#1]
https://github.com/Assuner-Lee/Stinger

**Comment by yulingtianxia** [comment]
@Assuner-Lee 理论上能替换 C 函数，就能 hook 很多东西。当然 hook objc 的方法可以利用 runtime 机制更方便地实现。如果 Stinger 能在可用性和性能等方面更占优势，利用 libffi 来 hook 方法确实是个很好的思路。目前最大的缺点是需引入 libffi，BlockHook 也一样。不过因为 block 没法直接利用 runtime 来 hook，只能退而求其次了。

**Comment by Assuner-Lee** [comment]
当时只是为了保留aspects的AOP易用性，但又不想用笨重的消息转发... 相比aspects从发送消息到执行到hook信息确实会快一个数量级，不过确实引入libffi是个问题。

**Comment by yulingtianxia** [comment]
@Assuner-Lee  关于性能差一个数量级有没有 benchmark 呢？如果效果明显，确实是个空间换时间的策略。不过感觉应该方法执行效率上跟 Method Swizzling 没差多少吧，但是比在消息转发流程 hook 的方式要快。

**Comment by Assuner-Lee** [comment]
简单测过aspects和我写的那个，从发送消息到执行到第一个before block内部，会快很多，只能说是一种实现方式吧。

**Comment by yulingtianxia** [comment]
@Assuner-Lee 感觉本质上跟method swizzling一样是替换imp，也都有着相对于消息转发的速度优势和依赖继承链hook顺序的缺陷。但使用libffi动态特性能够提供hook的通用API。凡是能多次hook的就涉及多次替换imp，remove的时候就要逆序，很容易出问题。总之hook的确是个大坑。
