### ISSUE TITLE
关于Global类型Block会奔溃问题

### ISSUE THREAD

**Issue by jiangleligejiang** [yulingtianxia/BlockHook#11]
代码如下：
```objc
- (void)blockHookTest {
 
    int (^block)(int, int) = ^int(int x, int y) {
       int result = x + y;
       NSLog(@"%d + %d = %d", x, y, result);
       return result;
    };
        
    BHToken *tokenBefore = [block block_hookWithMode:BlockHookModeBefore usingBlock:^(BHInvocation *invocation, int x, int y){
        NSLog(@"hook block before");
    }];
    
    block(3, 5);
    
    [tokenBefore remove];
}
```
运行后，会导致此处奔溃：
![image](https://user-images.githubusercontent.com/41557745/82903191-310a7800-9f93-11ea-807d-a49ca1103bf0.png)
若block修改为Malloc类型的话，就能正常hook。

麻烦解答一下这个问题，感谢~

**Comment by yulingtianxia** [comment]
@jiangleligejiang 麻烦能提供一个能复现的 Demo 工程么？我这里直接用上面的代码没有复现。或者提供下更详细的信息，比如 Xcode 版本，运行环境（模拟器 or 真机机型）

顺便问下 `dbpd` 的值是 `0x0` 么？

**Comment by yulingtianxia** [comment]
![image](https://user-images.githubusercontent.com/433320/82912863-26a2ab00-9fa0-11ea-8d79-cc31ca21a154.png)
@jiangleligejiang 看截图里你使用的是旧版本的 BlockHook，新版本已经修复了，请更新下哈

**Comment by jiangleligejiang** [comment]
感谢回复~
demo工程可以在[这里](https://github.com/jiangleligejiang/JOCDemos)下载，运行`LibffiViewController`内容即可

目前尝试模拟器和真机都会有问题，显示的debug信息如下：
![image](https://user-images.githubusercontent.com/41557745/82984958-b76f9a00-a025-11ea-97d2-e65815e0f63f.png)

**Comment by yulingtianxia** [comment]
@jiangleligejiang 可以复现了，不过不是在这一行，我看看

**Comment by yulingtianxia** [comment]
@jiangleligejiang 这是 iOS 13 的问题，把 target iOS 版本调整到 12.4 及以下就可以正常工作。
![image](https://user-images.githubusercontent.com/433320/82994894-7089a080-a035-11ea-8484-4c98a00b21d7.png)

**Comment by jiangleligejiang** [comment]
> @jiangleligejiang 这是 iOS 13 的问题，把 target iOS 版本调整到 12.4 及以下就可以正常工作。
> ![image](https://user-images.githubusercontent.com/433320/82994894-7089a080-a035-11ea-8484-4c98a00b21d7.png)

我这边尝试用12.4版本的模拟器也存在这个问题

![image](https://user-images.githubusercontent.com/41557745/82997305-c7dd4000-a038-11ea-8472-12904a3e1e0e.png)

**Comment by yulingtianxia** [comment]
@jiangleligejiang 我这边用 Xcode 11.5 ，target iOS 12.4 ，模拟器是 iPhone 8 Plus，运行 OK。麻烦能帮忙试下必现的场景么？可能还有其他没考虑到的环境信息。

**Comment by jiangleligejiang** [comment]
> @jiangleligejiang 我这边用 Xcode 11.5 ，target iOS 12.4 ，模拟器是 iPhone 8 Plus，运行 OK。麻烦能帮忙试下必现的场景么？可能还有其他没考虑到的环境信息。

找到原因，是我这边的环境问题😂，之前设置了`Address Sanitizer`导致的，关闭了就正常了，辛苦作者了🙏

**Comment by yulingtianxia** [comment]
没事，你也帮我发现了新的问题，感谢反馈

**Comment by jiangleligejiang** [comment]
新问题指的是，hook global类型的block这里修改invoke会导致野指针问题？之前遇到过一次这里导致的crash，所以才加的Address Sanitizer，不过后来又没复现过了。
![image](https://user-images.githubusercontent.com/41557745/83001913-f5c58300-a03e-11ea-8280-9900d8c72075.png)

**Comment by yulingtianxia** [comment]
这个问题是 target 在 iOS 13 上必现的，lldb memory write 是可以的，但是代码里直接赋值就不行。估计是只读，还没细看。

**Comment by yulingtianxia** [comment]
@jiangleligejiang 1.5.8 版本已经修复 Address Sanitizer 的问题了。
