### ISSUE TITLE
Archive fail in Xcode12.1

### ISSUE THREAD

**Issue by ventus111** [yulingtianxia/BlockHook#14]
Xcode alert following error when archive:
bitcode bundle could not be generated because  '.../Pods/BlockHook/libffi/libffi_bh.a(ffi_arm.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by yulingtianxia** [comment]
@ventus111 You can turn off bitcode on you App. When your app depends on framework without bitcode, Xcode will give you this error.

**Comment by ventus111** [comment]
it works, thanks a lot!
