### ISSUE TITLE
跑了下demo  ffi_status = FFI_BAD_ABI

### ISSUE THREAD

**Issue by victorylau** [yulingtianxia/BlockHook#2]
文档上写  FFI_BAD_ABI if the abi parameter is invalid.

萌新不太懂。。。请大神指教

**Comment by yulingtianxia** [comment]
@victorylau 试试真机

**Comment by victorylau** [comment]
@yulingtianxia 真机可以，昨天测试CLI也可以，就模拟器不行。。。

**Comment by yulingtianxia** [comment]
@victorylau 目前模拟器确实有问题，即便替换静态链接库为 x86 的也不行，是 libffi 不支持 iOS x86 的问题。

**Comment by victorylau** [comment]
谢谢！学习到了。

**Comment by awaylyr** [comment]
我看了一下jspatch，创建ffi_cif的那个接口模拟器并不会有"FFI_BAD_ABI"的问题，有可能这里的传入参数获取有问题吗？
