### ISSUE TITLE
有个问题请教一下，谢谢

### ISSUE THREAD

**Issue by zengzihao4560** [yulingtianxia/BlockHook#3]
我的需求是hook UIAlertAction里的点击block回调，用BlockHook的过程中碰到了self.block提前被释放，导致crash。我不知道是因为UIAlertController被释放的原因还是其他的原因.

**Comment by yulingtianxia** [comment]
@zengzihao4560 能贴下堆栈信息么？如果不用 BlockHook 还会 crash 么？

**Comment by zengzihao4560** [comment]
不用的话是不会的。
![image](https://user-images.githubusercontent.com/19251465/44191518-5b909580-a15e-11e8-8b2a-ff899eab1bb3.png)

**Comment by yulingtianxia** [comment]
@zengzihao4560 能发下你的代码和堆栈么

**Comment by zengzihao4560** [comment]
@yulingtianxia  你好，发了一份demo给你g邮箱，有时间的话查收下。再次感谢

**Comment by yulingtianxia** [comment]
![image](https://user-images.githubusercontent.com/433320/44195016-5df8ec80-a16a-11e8-814b-0b9cabf7fcf2.png)
@zengzihao4560  这样改就 OK 了

**Comment by zengzihao4560** [comment]
@yulingtianxia  我按照你说的改了， 但是这样改就不会红框内的方法了。
![image](https://user-images.githubusercontent.com/19251465/44195445-a95fca80-a16b-11e8-85cb-8cc437edf518.png)

**Comment by yulingtianxia** [comment]
@zengzihao4560 原因是这个 block 是栈 block 不是堆 block，手动 copy 下就可以。我会发个版本修复做下保护。
![image](https://user-images.githubusercontent.com/433320/44210323-b646e300-a198-11e8-9057-0aa1ed6adafd.png)

**Comment by zengzihao4560** [comment]
@yulingtianxia   问题已经解决，多谢大佬！！！
