### ISSUE TITLE
'fficonfig.h' file not found

### ISSUE THREAD

**Issue by Hank-Zhong** [yulingtianxia/BlockHook#4]
@yulingtianxia 
按照 [Example](https://github.com/yulingtianxia/BlockHook#-example) 操作后提示错误：`BlockHook/libffi/darwin_ios/src/x86/unix64_x86_64.S:33:10: 'fficonfig.h' file not found`

**Comment by yulingtianxia** [comment]
@Hank-Zhong 我发现 Xcode 10.2 会有问题，尝试使用 Xcode 10.0 试试？

**Comment by Hank-Zhong** [comment]
啊哈！后面用libffi项目手动生成.a文件并且手动导入项目里了

**Comment by yulingtianxia** [comment]
已经修复
