### ISSUE TITLE
ffi_call_int 概率crash

### ISSUE THREAD

**Issue by lienbao** [yulingtianxia/BlockHook#6]
void xm_dispatch_async(dispatch_queue_t queue, dispatch_block_t block) {
    
    if (__enable) {
        
        dispatch_block_t chgBlock = block;
        if ([block isKindOfClass:NSClassFromString(@"__NSStackBlock")]) {
            chgBlock = [block copy];
        }
        
        [chgBlock block_hookWithMode:BlockHookModeInstead
                          usingBlock:^(BHToken *token){
                                  
                                  double begin = [[NSDate date] timeIntervalSince1970];
                                  [token invokeOriginalBlock];
                                  double end = [[NSDate date] timeIntervalSince1970];
                                  //[token remove];
                                  
                                  [[XMAPMCPUMonitor monitor] setThread:[NSThread currentThread]
                                                            beginStamp:begin
                                                              endStamp:end];
                                  
                              }];
    }
    
    orig_dispatch_async(queue, block);
    
}

hook掉 gcd创建方法，在hook block中调用之前的blok会有一定概率crash

0	0x0000000105400a38	ffi_call_int + 276 
1	0x00000001040d886c	-[BHToken invokeOriginalBlock] + 180 
2	0x00000001040d886c	-[BHToken invokeOriginalBlock] + 180 
3	0x000000010442dc78	__xm_dispatch_async_block_invoke + 160

**Comment by yulingtianxia** [comment]
@lienbao xm_dispatch_async 是用 fishhook 了么？ 能麻烦提供下demo 么？

**Comment by lienbao** [comment]
demo功能很简单，你有邮箱或者其他聊天工具吗？我这边发给你

**Comment by lienbao** [comment]
再和你说一下详细的情况

**Comment by yulingtianxia** [comment]
@lienbao yulingtianxia@gmail.com

**Comment by yulingtianxia** [comment]
从堆栈来看，是 Block 自身执行的时候发生了 crash。大部分都发生在 Dealloc 方法里做了其他事情（如读写 IO）。不确定与 BlockHook 组件本身是否有关系，持续观察中。。。

**Comment by lienbao** [comment]
我这边有毕现的路径，等明天我和你说一下，看看问题出在哪？我今天忙一下别的，抱歉哈




| |
lienbao
邮箱：lienbaoleb@163.com
|

Signature is customized by Netease Mail Master

在2019年05月07日 19:32，杨萧玉 写道：

从堆栈来看，是 Block 自身执行的时候发生了 crash。大部分都发生在 Dealloc 方法里做了其他事情（如读写 IO）。不确定与 BlockHook 组件本身是否有关系，持续观察中。。。

**Comment by yulingtianxia** [comment]
原因是 args 和 ret 在 token 上多线程读写的问题，改动需要修改接口，下个版本修复。

**Comment by yulingtianxia** [comment]
Fixed in 1.2.4: https://github.com/yulingtianxia/BlockHook/releases/tag/1.2.4
