### ISSUE TITLE
BHFFIClosureFunc

### ISSUE THREAD

**Issue by flyingDandelionYD** [yulingtianxia/BlockHook#8]
现在 我需要hook网络接口返回的block，发现  如果是 __NSMallocBlock__    捕获到里面BHFFIClosureFunc 不走  不知道为啥？

**Comment by yulingtianxia** [comment]
@flyingDandelionYD 没太看懂问题，麻烦能描述详细些，或者附上 demo 么？或使用最新版试试？

**Comment by flyingDandelionYD** [comment]
@yulingtianxia  
==================
其中：TYWGSDKAPI 这里sdk里面封装的类方法
```
+ (void)getDevciesConnectedToGateway:(NSString *)mac
                             Success:(TYWG_SuccessBlock)successBlock
                              Failed:(TYWG_FailedBlock)failedBlock;
```
使用：
```
Class tywgSDKAPI = objc_getMetaClass(NSStringFromClass(TYWGSDKAPI.class).UTF8String);
[tywgSDKAPI aspect_hookSelector:@selector(getDevciesConnectedToGateway:Success:Failed:) withOptions:AspectPositionAfter usingBlock:^(id<AspectInfo> aspectInfo){
        NSLog(@"%@",aspectInfo.arguments);
        NSLog(@"successBlock=>%@",[aspectInfo.arguments objectAtIndex:[aspectInfo.arguments count]-2]);
        //成功回调
        [[aspectInfo.arguments objectAtIndex:[aspectInfo.arguments count]-2] block_hookWithMode:BlockHookModeAfter usingBlock:^(BHInvocation *invocation,id res){
            NSLog(@"%@",res);
        }];
        NSLog(@"failedBlock=>%@",aspectInfo.arguments.lastObject);
        //失败回调
        [aspectInfo.arguments.lastObject block_hookWithMode:BlockHookModeAfter usingBlock:^(BHInvocation *invocation,NSError* error){
            NSLog(@"%@",error);
        }];
    } error:NULL];
}
```
我在打断的时候发现：successBlock 一个mallocBlock的类型 ，然后 他就不走BHFFIClosureFunc里面的方法，不知道问题出在哪里。。 
麻烦看看呢。。PS   远程也可以呢

**Comment by yulingtianxia** [comment]
@flyingDandelionYD 可以看看马上要 hook 之前，block 是哪个对象。执行的时候可能已经是另外一个 block 对象了。
如果 `getDevciesConnectedToGateway` 方法同步调用了 block，那么 hook 的时候 block 已经执行完了。用 `AspectPositionAfter` 时机就晚了。

**Comment by flyingDandelionYD** [comment]
@yulingtianxia  发现他会提前走 BlockHook.m里面的dealloc方法 然后在走的是我接口成功的api的回调    问下 啥时候 会提前走dealloc方法？

**Comment by flyingDandelionYD** [comment]
![image](https://user-images.githubusercontent.com/32588348/60191007-31236480-9866-11e9-9398-95e433a52c8c.png)
@yulingtianxia

**Comment by yulingtianxia** [comment]
> @yulingtianxia 发现他会提前走 BlockHook.m里面的dealloc方法 然后在走的是我接口成功的api的回调 问下 啥时候 会提前走dealloc方法？

因为你 Hook 了成功和失败两个 block，而只调用其中一个，肯定会有一个没被调用就 dealloc。当 block 销毁的时候，blockhook 也会 dealloc。建议先只 hook 那个会被调用的 block，有利于排查问题。

**Comment by flyingDandelionYD** [comment]
嗯嗯  不过刚刚试了 我只hook了成功的block。还是会提前走dealloc方法   😭😭
![image](https://user-images.githubusercontent.com/32588348/60192354-4c8f6f00-9868-11e9-87c3-83f47235d3d8.png)
不知道会不会跟 hook进去的是__NSMallocBlock__有关
@yulingtianxia

**Comment by yulingtianxia** [comment]
@flyingDandelionYD 你用的是啥版本呢？能确认下成功的 block 在 hook 前和调用时是同一个对象么？
跟 __NSMallocBlock__ 没关系的。
你可以吧 success 的 block 先作为一个局部变量写出来，然后 hook 它，再把它传给 `getDevciesConnectedToGateway` 方法试试。

**Comment by flyingDandelionYD** [comment]
用的最新的版本   今天刚刚pod的  0.0  
![image](https://user-images.githubusercontent.com/32588348/60192857-3504b600-9869-11e9-9796-bc516dc702ef.png)
图上面的  应该是同一个对象吧

如果不好看的话  可以远程下吗？ 大佬
@yulingtianxia

**Comment by yulingtianxia** [comment]
> 用的最新的版本 今天刚刚pod的 0.0
> ![image](https://user-images.githubusercontent.com/32588348/60192857-3504b600-9869-11e9-9796-bc516dc702ef.png)
> 图上面的 应该是同一个对象吧
> 
> 如果不好看的话 可以远程下吗？ 大佬
> @yulingtianxia

因为不了解 `getDevciesConnectedToGateway` 内部的机制，如果能到这个方法里断点看下，在 success 执行前看下 block 对象就好了。或者搞个能复现的 demo 工程出来。

**Comment by yulingtianxia** [comment]
@flyingDandelionYD 远程不太方便。可以先把 block 作为局部变量 hook 后再当参数传进去试试，排除 Aspects 的干扰。也可以看看 hook 返回的 token 是否有内容，以及 hook 过程中的 log 是否报错。

**Comment by flyingDandelionYD** [comment]
嗯嗯 好的   不过它是sdk提供的根本没法在里面定位   明儿问下   3Q  0.0

**Comment by flyingDandelionYD** [comment]
大佬发现    如果里面有self的引用就会不走hook的方法.  如果没有就会走  
具体的demo：https://pan.baidu.com/s/1OFjeMl0MK-AdnXnvfTixoQ   麻烦帮看看呢 (在viewController里面).  3Q
@yulingtianxia

**Comment by yulingtianxia** [comment]
@flyingDandelionYD Aspects 有问题，果然是我说的问题：Hook 的 block 对象与传给 `getDevciesConnectedToGateway` 方法的对象不是同一个。也就是说 Aspects 在 Hook 后，传给你的 block 参数已经不是最开始的那个对象了。直接用我的 [BlockTracker](https://github.com/yulingtianxia/BlockTracker)  组件就可以满足你的需求，它基于 BlockHook 的。

**Comment by flyingDandelionYD** [comment]
@yulingtianxia  大佬用了 BlockTracker 方法    还是发现有问题    不是会蹦就是不走   😢  
https://pan.baidu.com/s/1rKJ047yhqt0hZdmyZhkFHQ  这是Demo的地址，麻烦看看呢   3Q

**Comment by yulingtianxia** [comment]
> @yulingtianxia 大佬用了 BlockTracker 方法 还是发现有问题 不是会蹦就是不走 😢
> https://pan.baidu.com/s/1rKJ047yhqt0hZdmyZhkFHQ 这是Demo的地址，麻烦看看呢 3Q
1.  崩溃是因为接口改了，你的太旧了，需要更新到最新版。你需要 `pod update`
2. 把 Aspects 的逻辑注释掉就好了。

**Comment by flyingDandelionYD** [comment]
@yulingtianxia  嗯嗯 我更新了的最新的代码 可以拦截到block回调了 👍👍👍
但是有几个问题想请教一下呢
1.现在是可以拦截到block了，那怎么拿到block的回调的值呢，也就是说我需要拿到从接口里面回调成功的数据 ？
2.现在我有一个需求，当类方法调用网络接口的时候，我需要【同时】知道接口传的参数的值，以及接口的回调的值（成功/失败）？
PS：我现在  通过 Aspects已经拿到接口传的参数值了以及传的block了，但是，我在外面写bt_trackBlockArgOfSelector的方法，拿不到接口返回的成功的值（失败的值），而且我同时写Aspects和bt_trackBlockArgOfSelector方法，会发现Aspects的hook会走2遍.

**Comment by yulingtianxia** [comment]
@flyingDandelionYD 
1 nsinvocation 里有参数和返回值，可以修改
2 不建议使用aspects，这个库问题太多

**Comment by flyingDandelionYD** [comment]
@yulingtianxia  用你的思路   现在可以拦截请求参数值和回调的值了   谢谢啦 大佬 3Q  👍

**Comment by yulingtianxia** [comment]
> @yulingtianxia 用你的思路 现在可以拦截请求参数值和回调的值了 谢谢啦 大佬 3Q 👍

嗯那这个 issue 可以关了。
